version: "3"
services:
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test_root_secret
            MYSQL_USER: test_user
            MYSQL_PASSWORD: test_secret
            MYSQL_DATABASE: test_db
    server:
        restart: always
        build:
            context: ./server
        ports:
            - "3001:3001"
        env_file:
            - ./server/config/.env
        depends_on:
            - db
        volumes:
            - ./server/src:/usr/app/src
            - ./server/tests:/usr/app/tests
    ui:
        restart: always
        build:
            context: ./ui
        ports: 
            - "3000:3000"
        volumes:
            - ./ui/src:/usr/app/src
        stdin_open: true