env:
  commonjs: true
  es6: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - off 
  node/no-deprecated-api:
    - error
  node/no-extraneous-require:
    - off
  node/no-unpublished-require:
    - error 
    - allowModules:
        - mocha
        - chai
        - chai-http