module.exports.CREDIT_TRANSACTION = 'credit'
module.exports.DEBIT_TRANSACTION = 'debit'
module.exports.CONCURRENCY_ERROR = 'You can only perform one transaction at a time, please try again in a few seconds.'
module.exports.INVALID_TRANSACTION = 'Invalid transaction type, please use credit/debit.'
module.exports.NO_FUNDS = 'Not enough founds.'
module.exports.INVALID_AMOUNT = 'Value "amount" must be a positive number.'
module.exports.NOT_FOUND = 'Transaction not found, please check the provided id.'